#!/usr/bin/env python3
"""
Extract GROMACS nblib API interfaces from local headers and update interface inventory.

One-shot script: extracts key interface signatures and updates the dossier.
"""

import re
import sys
from pathlib import Path
from typing import List, Dict

# Add repo root to path for imports if needed
repo_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(repo_root))

# Key headers to extract from
GROMACS_HEADERS = {
    'Topology': 'interfaces/gromacs/api/nblib/include/nblib/topology.h',
    'ListedForceCalculator': 'interfaces/gromacs/api/nblib/include/nblib/listed_forces/calculator.h',
    'GmxNBForceCalculatorCpu': 'interfaces/gromacs/api/nblib/include/nblib/gmxcalculatorcpu.h',
    'Interactions': 'interfaces/gromacs/api/nblib/include/nblib/interactions.h',
    'SimulationState': 'interfaces/gromacs/api/nblib/include/nblib/simulationstate.h',
}

TARGET_DOSSIER = repo_root / 'interfaces/gromacs/interface_inventory.md'


def extract_class_signatures(header_path: Path) -> Dict[str, List[str]]:
    """Extract public class methods and key declarations from a header."""
    if not header_path.exists():
        return {}
    
    content = header_path.read_text()
    
    signatures = []
    
    # Extract class definitions with their public methods
    # Look for class definitions
    class_match = re.search(r'class\s+(\w+)\s*(?:final)?\s*(?::\s*public\s+[\w\s,]+)?\s*\{', content)
    if not class_match:
        return {}
    
    class_name = class_match.group(1)
    
    # Extract public: section methods
    # Find public: sections
    public_sections = re.finditer(r'public:\s*\n((?:\s*(?:/\*.*?\*/)?\s*\n)*(?:.*?\n)*?)(?=\s*(?:private:|protected:|public:|};|$))', content, re.MULTILINE | re.DOTALL)
    
    for section in public_sections:
        public_block = section.group(1)
        
        # Extract method declarations (lines ending with ; or {)
        method_pattern = r'(\s*(?:/\*.*?\*/)?\s*(?:virtual\s+)?(?:~?\w+\s*\([^)]*\)(?:\s*const)?(?:\s*=\s*0)?\s*[;{]))'
        methods = re.findall(method_pattern, public_block, re.MULTILINE)
        
        for method in methods:
            # Clean up the method signature
            method_clean = re.sub(r'\s+', ' ', method.strip())
            method_clean = re.sub(r'/\*.*?\*/', '', method_clean).strip()
            if method_clean and not method_clean.startswith('//'):
                signatures.append(method_clean)
    
    # Also look for key typedefs, static methods, enums
    typedefs = re.findall(r'typedef\s+.*?(\w+)\s*;', content)
    static_methods = re.findall(r'static\s+.*?(\w+\s*\([^)]*\))\s*;', content)
    
    return {
        'class_name': class_name,
        'methods': signatures[:20],  # Limit to first 20 methods
        'typedefs': typedefs[:10],
        'static_methods': static_methods[:10],
    }


def extract_all_interfaces() -> Dict[str, Dict]:
    """Extract interfaces from all target headers."""
    results = {}
    
    for interface_name, rel_path in GROMACS_HEADERS.items():
        full_path = repo_root / rel_path
        if full_path.exists():
            print(f"Extracting from {full_path}...")
            results[interface_name] = extract_class_signatures(full_path)
        else:
            print(f"Warning: {full_path} not found")
    
    return results


def format_extracted_api(extracted: Dict[str, Dict]) -> str:
    """Format extracted API into markdown."""
    lines = [
        "<!-- AUTO:GROMACS_API_START -->",
        "",
        "## Auto-extracted GROMACS nblib interfaces (from local headers)",
        "",
        "Generated by `interfaces/tools/gromacs_extract_and_update.py`.",
        "",
    ]
    
    for name, data in extracted.items():
        if not data or 'class_name' not in data:
            continue
            
        lines.append(f"### `{data['class_name']}` ({name})")
        lines.append("")
        
        if data.get('methods'):
            for method in data['methods']:
                if method and len(method) < 200:  # Skip very long lines
                    lines.append(f"- `{method}`")
            lines.append("")
        
        if data.get('typedefs'):
            lines.append("**Typedefs:**")
            for td in data['typedefs']:
                lines.append(f"- `{td}`")
            lines.append("")
    
    lines.append("<!-- AUTO:GROMACS_API_END -->")
    
    return "\n".join(lines)


def update_dossier(content_marker: str, new_content: str):
    """Update the dossier file between AUTO markers."""
    if not TARGET_DOSSIER.exists():
        # Create new file
        TARGET_DOSSIER.parent.mkdir(parents=True, exist_ok=True)
        TARGET_DOSSIER.write_text(new_content + "\n")
        print(f"Created new dossier at {TARGET_DOSSIER}")
        return
    
    content = TARGET_DOSSIER.read_text()
    
    # Find and replace between markers
    pattern = rf'({re.escape(content_marker)}.*?){re.escape(content_marker.replace("START", "END"))}'
    
    if re.search(pattern, content, re.DOTALL):
        # Replace existing section
        new_file_content = re.sub(pattern, new_content, content, flags=re.DOTALL)
        TARGET_DOSSIER.write_text(new_file_content)
        print(f"Updated existing AUTO section in {TARGET_DOSSIER}")
    else:
        # Append new section
        TARGET_DOSSIER.write_text(content + "\n\n" + new_content + "\n")
        print(f"Appended new AUTO section to {TARGET_DOSSIER}")


def main():
    print("Extracting GROMACS nblib interfaces...")
    extracted = extract_all_interfaces()
    
    formatted = format_extracted_api(extracted)
    
    if '--update-dossier' in sys.argv:
        update_dossier("<!-- AUTO:GROMACS_API_START -->", formatted)
    else:
        print("\n" + "="*80)
        print(formatted)
        print("\n(Use --update-dossier to write to dossier)")


if __name__ == '__main__':
    main()
