#!/usr/bin/env python3
"""
One-shot LAMMPS interface extraction from locally cloned repo.

Reads key headers from interfaces/lammps and writes:
  - interfaces/lammps/EXTRACTED_API.md
  - updates interfaces/lammps/interface_inventory.md between:
      <!-- AUTO:LAMMPS_API_START -->
      <!-- AUTO:LAMMPS_API_END -->

No third-party dependencies (stdlib only).
"""

from __future__ import annotations

import argparse
from pathlib import Path


LAMMPS_ROOT = Path("interfaces/lammps")

TARGET_HEADERS = {
    "Pair": LAMMPS_ROOT / "src/pair.h",
    "Fix": LAMMPS_ROOT / "src/fix.h",
    "Modify": LAMMPS_ROOT / "src/modify.h",
}


def _read(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def _find_lines(txt: str, needles: list[str], max_hits: int = 60) -> list[str]:
    out: list[str] = []
    for line in txt.splitlines():
        if any(n in line for n in needles):
            out.append(line.strip())
            if len(out) >= max_hits:
                break
    return out


def extract_lammps_api() -> str:
    lines: list[str] = []
    lines.append("## Auto-extracted LAMMPS interfaces (from local headers)")
    lines.append("")
    lines.append("Generated by `interfaces/tools/lammps_extract_and_update.py`.")
    lines.append("")

    pair = _read(TARGET_HEADERS["Pair"])
    fix = _read(TARGET_HEADERS["Fix"])
    modify = _read(TARGET_HEADERS["Modify"])

    lines.append("### `Pair` (pair style base)")
    lines.append("")
    for l in _find_lines(pair, ["class Pair", "compute(", "single(", "manybody_flag", "init(", "setup("]):
        lines.append(f"- `{l}`")
    lines.append("")

    lines.append("### `Fix` (timestep/lifecycle hook base)")
    lines.append("")
    for l in _find_lines(fix, ["class Fix", "pre_force", "post_force", "end_of_step", "initial_integrate", "final_integrate"]):
        lines.append(f"- `{l}`")
    lines.append("")

    lines.append("### `Modify` (orchestrates active Fix/Compute lists)")
    lines.append("")
    for l in _find_lines(modify, ["class Modify", "Fix **fix", "Compute **compute", "add_fix", "delete_fix", "pre_force", "post_force"]):
        lines.append(f"- `{l}`")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def update_between_markers(path: Path, start: str, end: str, block: str) -> None:
    txt = path.read_text(encoding="utf-8", errors="replace")
    if start not in txt or end not in txt:
        raise RuntimeError(f"Missing markers in {path}. Expected {start} and {end}.")
    pre, rest = txt.split(start, 1)
    _, post = rest.split(end, 1)
    out = pre + start + "\n\n" + block + "\n" + end + post
    path.write_text(out, encoding="utf-8", newline="\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--update-dossier", action="store_true")
    args = ap.parse_args()

    for name, p in TARGET_HEADERS.items():
        if not p.exists():
            raise FileNotFoundError(f"Missing {name} header at {p}")

    api = extract_lammps_api()
    out_md = LAMMPS_ROOT / "EXTRACTED_API.md"
    out_md.write_text(api, encoding="utf-8", newline="\n")
    print(f"Wrote: {out_md}")

    if args.update_dossier:
        inv = LAMMPS_ROOT / "interface_inventory.md"
        update_between_markers(inv, "<!-- AUTO:LAMMPS_API_START -->", "<!-- AUTO:LAMMPS_API_END -->", api)
        print(f"Updated: {inv}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

