#!/usr/bin/env python3
"""
One-shot OpenMM interface extraction from locally cloned repo.

Reads key headers from interfaces/openmm and writes:
  - interfaces/openmm/EXTRACTED_API.md
  - updates interfaces/openmm/interface_inventory.md between:
      <!-- AUTO:OPENMM_API_START -->
      <!-- AUTO:OPENMM_API_END -->

"""

from __future__ import annotations

import argparse
from pathlib import Path


OPENMM_ROOT = Path("interfaces/openmm")

TARGET_HEADERS = {
    "Force": OPENMM_ROOT / "openmmapi/include/openmm/Force.h",
    "System": OPENMM_ROOT / "openmmapi/include/openmm/System.h",
    "Context": OPENMM_ROOT / "openmmapi/include/openmm/Context.h",
    "Platform": OPENMM_ROOT / "olla/include/openmm/Platform.h",
    "Kernel": OPENMM_ROOT / "olla/include/openmm/Kernel.h",
}


def _read(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def _find_lines(txt: str, needles: list[str], max_hits: int = 40) -> list[str]:
    out: list[str] = []
    for line in txt.splitlines():
        if any(n in line for n in needles):
            out.append(line.strip())
            if len(out) >= max_hits:
                break
    return out


def extract_openmm_api() -> str:
    lines: list[str] = []
    lines.append("## Auto-extracted OpenMM interfaces (from local headers)")
    lines.append("")
    lines.append("Generated by `interfaces/tools/openmm_extract_and_update.py`.")
    lines.append("")

    force = _read(TARGET_HEADERS["Force"])
    system = _read(TARGET_HEADERS["System"])
    context = _read(TARGET_HEADERS["Context"])
    platform = _read(TARGET_HEADERS["Platform"])
    kernel = _read(TARGET_HEADERS["Kernel"])

    lines.append("### `Force` (term front-end)")
    lines.append("")
    for l in _find_lines(force, ["class Force", "createImpl", "usesPeriodicBoundaryConditions", "setForceGroup", "getForceGroup"]):
        lines.append(f"- `{l}`")
    lines.append("")

    lines.append("### `System` (system composition)")
    lines.append("")
    for l in _find_lines(system, ["class System", "addParticle", "addForce", "addConstraint", "setVirtualSite", "getNumParticles"]):
        lines.append(f"- `{l}`")
    lines.append("")

    lines.append("### `Context` (runtime binding)")
    lines.append("")
    for l in _find_lines(context, ["class Context", "getState", "setPositions", "setVelocities", "setParameter", "getPlatform"]):
        lines.append(f"- `{l}`")
    lines.append("")

    lines.append("### `Platform` (backend registry)")
    lines.append("")
    for l in _find_lines(platform, ["class Platform", "findPlatform", "createKernel", "getProperty", "setProperty", "KernelFactory"]):
        lines.append(f"- `{l}`")
    lines.append("")

    lines.append("### `Kernel` (backend unit)")
    lines.append("")
    for l in _find_lines(kernel, ["class Kernel", "execute", "getName", "getImpl", "KernelImpl"]):
        lines.append(f"- `{l}`")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def update_between_markers(path: Path, start: str, end: str, block: str) -> None:
    txt = path.read_text(encoding="utf-8", errors="replace")
    if start not in txt or end not in txt:
        raise RuntimeError(f"Missing markers in {path}. Expected {start} and {end}.")
    pre, rest = txt.split(start, 1)
    _, post = rest.split(end, 1)
    out = pre + start + "\n\n" + block + "\n" + end + post
    path.write_text(out, encoding="utf-8", newline="\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--update-dossier", action="store_true")
    args = ap.parse_args()

    # sanity check headers exist
    for name, p in TARGET_HEADERS.items():
        if not p.exists():
            raise FileNotFoundError(f"Missing {name} header at {p}")

    api = extract_openmm_api()
    out_md = OPENMM_ROOT / "EXTRACTED_API.md"
    out_md.write_text(api, encoding="utf-8", newline="\n")
    print(f"Wrote: {out_md}")

    if args.update_dossier:
        inv = OPENMM_ROOT / "interface_inventory.md"
        update_between_markers(inv, "<!-- AUTO:OPENMM_API_START -->", "<!-- AUTO:OPENMM_API_END -->", api)
        print(f"Updated: {inv}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

